services:
  traefik:
    image: docker.io/traefik:v3.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/docker/local/traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - bank_fraud_detection_local_nw
    command:
      - --providers.docker

  api:
    build:
      context: .
      dockerfile: ./backend/docker/local/fastapi/Dockerfile
    volumes:
      - .:/src
      - ./backend/app/logs:/src/backend/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/envs/.env.local
    depends_on:
      - postgres
    command: /start.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.service=api-service"
      - "traefik.http.services.api-service.loadbalancer.server.port=8000"
      - "traefik.http.services.api-service.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.api-service.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.api-service.loadbalancer.healthcheck.timeout=5s"
    networks:
      - bank_fraud_detection_local_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - bankfraud_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCPEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - bank_fraud_detection_local_nw

  postgres:
    build:
      context: .
      dockerfile: backend/docker/local/Postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - bank_fraud_detection_local_db:/var/lib/postgresql/data
    env_file:
      - ./backend/app/envs/.env.local
    networks:
      - bank_fraud_detection_local_nw

networks:
  bank_fraud_detection_local_nw:
    external: true

volumes:
  bank_fraud_detection_local_db: {}
  bankfraud_mailpit_data: {}
